name = "Joban Modpack"
author = "LX86"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e47d70781a2f4ba0b124f7d7f9b3c556465c9164476d56bac260e972ad0e1f35"

[versions]
fabric = "0.16.9"
minecraft = "1.19.4"

[options]
acceptable-game-versions = ["1.19.4"]
