name = "Joban Modpack"
author = "LX86"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "838e61b7d199e4026c0d2817b321c941f925101da88f1dbe1821f95832b5fdb0"

[versions]
fabric = "0.16.9"
minecraft = "1.19.4"

[options]
acceptable-game-versions = ["1.19.4"]
