name = "Joban Modpack"
author = "LX86"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "396ce1611d57c2bfd8371e876d758d6e2c5d890f8f8d0d3c03fcc348a43513f7"

[versions]
fabric = "0.15.3"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
