name = "Joban Modpack"
author = "LX86"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6aa60e69a2793b455f90b50ff96759ae1ba1788e79620c61f5d3e5b5a1db3559"

[versions]
fabric = "0.16.2"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
