name = "Joban Modpack"
author = "LX86"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "11ed7192f55bd79c0d1182d2c3d59f5730f7f02abdeee499cf9d42d4e478cafd"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
