name: Update mods
on:
  # Triggers the workflow every 2 hours
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"
 
jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Get Current Date
        run: echo "CURDATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
      - name: Install dependencies
        run: npm install
      - name: Execute update check
        id: updchk
        continue-on-error: true
        run: node index.js
      - name: Commit back cache file
        if: ${{ steps.updchk.outcome == 'success' }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
            file_pattern: '*.json'
            commit_message: 'Update modpack cache'
      - name: Create release
        if: ${{ steps.updchk.outcome == 'success' }}
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          tag_name: ${{ env.CURDATE }}
          fail_on_unmatched_files: true
          files: modpack.zip
